### PR TITLE
Slovak Translation

### PR DESCRIPTION
**Pull request by MatejGolian**
I have translated the program to Slovak. The file seems to be OK, but some of the strings just refuse to display in other than English. The line "3=Recreate seek table for: %s. \nThis can take up to 20 seconds, please wait a moment." in the DIALOG_3 section is a particularly good example of this.
If you can, please, examine this issue further.

### CODE REVIEW

**Comment by imgdrive** [comment]
My fault, i forgot to update strings in DIALOG_3

**Comment by MatejGolian** [comment]
I'm glad you sorted it out.
The mount dialog, when launched from the tray menu, suffers from the same issue. I have the language set to my translation and still the strings "All image files (*.ccd;*.cue;*.iso;*.isz;*.mds;*.nrg)" and "All files (*.*)" in the file type combo box show in English.

**Comment by imgdrive** [comment]
Got it.

new .ini files had committed, test with this new internal build: http://download.yubsoft.com/imgdrive.zip

**Comment by MatejGolian** [comment]
Thank you, DIALOG_3 shows as expected now, but the issue with the mount dialog in the tray menu that I mentioned in my previous comment still persists. Based on the ini files I'd guess that that dialog uses a different set of strings - ones not present in the language files. Actually, to me it seems that from a technical point of view, the mount dialog in the tray menu is not the same as the mount dialog that appears after right-clicking a drive in Windows Explorer - the file type selector in the first dialog lists 8 options while the one invoked from the Explorer context menu only lists 2. What's more important, the dialog called from Explorer gets translated properly, while the dialog in the tray menu does not. If these are indeed 2 different dialogs, wouldn't it be more practical to use the same dialog in both cases? If one of those dialogs can be discarded, I propose keeping the one currently in the Explorer context menu.
Otherwise, the development version seems to perform much better than the stable one.

**Comment by imgdrive** [comment]
Shell extension uses different strings, 6 and 7 in [STRING] section, they should use the same string. 

New beta version which use the same string:
http://download.yubsoft.com/ImgDrive_1.2.2_beta.exe

**Comment by MatejGolian** [comment]
Thank you, seems to work just fine. :-)

**Pull request merged**
